# Generated by Django 3.1 on 2023-02-20 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mosque_date_created', models.DateTimeField(auto_created=True)),
                ('mosque_name', models.CharField(max_length=150)),
                ('mosque_focal_point', models.CharField(max_length=150)),
                ('mosque_address', models.CharField(blank=True, max_length=150)),
                ('mosque_email', models.EmailField(blank=True, max_length=150)),
                ('mosque_website', models.URLField(blank=True, max_length=150)),
                ('mosque_phone', models.IntegerField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')])),
                ('mosque_city', models.CharField(blank=True, max_length=150)),
                ('mosque_state', models.CharField(max_length=150)),
                ('mosque_bank_1', models.CharField(max_length=150)),
                ('mosque_account_1', models.IntegerField(max_length=10)),
                ('mosque_bank_2', models.CharField(blank=True, max_length=150)),
                ('mosque_account_2', models.IntegerField(blank=True, max_length=10)),
                ('mosque_bank_3', models.CharField(blank=True, max_length=150)),
                ('mosque_account_3', models.IntegerField(blank=True, max_length=10)),
                ('mosque_status', models.BooleanField(default=True)),
                ('mosque_date_disabled', models.DateTimeField(blank=True)),
                ('mosque_image', models.ImageField(blank=True, upload_to='mosques')),
            ],
        ),
    ]
