# Generated by Django 3.1 on 2023-02-20 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0002_auto_20230220_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mosque',
            old_name='mosque_account_1',
            new_name='mosque_account',
        ),
        migrations.RenameField(
            model_name='mosque',
            old_name='mosque_bank_1',
            new_name='mosque_bank',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='mosque_account_2',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='mosque_account_3',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='mosque_bank_2',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='mosque_bank_3',
        ),
    ]
