# Generated by Django 3.1 on 2023-02-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0003_auto_20230220_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='mosque_date_disabled',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
