# Generated by Django 3.1 on 2023-02-20 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosque', '0004_auto_20230220_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='mosque_phone',
            field=models.IntegerField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\1?\\d{9,10}$')]),
        ),
    ]
